"""User

Revision ID: 1dbe520134ed
Revises: 76bc5f298a7a
Create Date: 2022-09-25 17:46:39.151388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dbe520134ed'
down_revision = '76bc5f298a7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastdb_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_fastdb_users_id'), 'fastdb_users', ['id'], unique=True)
    op.add_column('fastdb_posts', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fastdb_posts', 'fastdb_users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fastdb_posts', type_='foreignkey')
    op.drop_column('fastdb_posts', 'user')
    op.drop_index(op.f('ix_fastdb_users_id'), table_name='fastdb_users')
    op.drop_table('fastdb_users')
    # ### end Alembic commands ###
